accounts/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

import accounts
from . import views

app_name="accounts"

urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.view_login,name='login'),
    path('logout/',views.logouting,name='logout'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),
    path('forgotpassword',views.forgotPassword,name='forgotpassword'),
    path('resetpassword_validate/<uidb64>/<token>/',views.resetpassword_validate,name='resetpassword_validate'),
    path('resetpassword/',views.resetpassword,name='resetpassword')

]

amazon_crawler/urls.py
from django.urls import path
from . import views

app_name = "amazon_crawler"

# URLConf
urlpatterns = [
    path('', views.home, name=''),
    path('best-selling/', views.home, name='best-selling'),
    path('download/<task_id>/', views.download_data, name='download_data'),
    path('download_amazon/<task_id>/', views.download_amazon, name='download_amazon'),
    path("EBP/",views.ebay_by_products, name='EBP'),
    path("ABP/",views.amazon_by_pro, name='ABP')

            ]

crawler/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from amazon_crawler import views
from amazon_crawler import views
from django.conf.urls.static import static
from django.conf import settings

from crawler.settings import MEDIA_ROOT

admin.site.site_header = "ParseJet"

urlpatterns = [ path('admin/', admin.site.urls),
                #apps
                path('crawlers/', include('amazon_crawler.urls')),
                path('', views.home),
                path('accounts/',include('accounts.urls')),
                path('__debug__/', include(debug_toolbar.urls)),
                
                
                ] + static(settings.MEDIA_URL,document_root=MEDIA_ROOT)
                

                

amazon_crawler/models.py
from django.db import models
from accounts.models import Account


class EbayByProduct(models.Model):
    title = models.CharField(max_length=300, null=True)
    price = models.CharField(max_length=20, null=True)
    rating = models.CharField(max_length=20, null=True)
    condition = models.CharField(max_length=250, null=True) 
    brand = models.CharField(max_length=250, null=True) 
    available_quantity = models.CharField(max_length=250, null=True)  
    sold_quantity = models.CharField(max_length=250, null=True) 
    img_url = models.CharField(max_length=250, null=True)
    product_url=models.CharField(max_length=250,null=True)  
    task_id = models.UUIDField(null=False)  
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE,
        related_name='user_account', null=False
    )  
    
    def __str__(self) -> str:
        return self.title or ""

    class Meta:
        ordering = ['title', 'price']



class AmazonByProduct(models.Model):
    title=models.CharField(max_length=300,null=True)
    price=models.CharField(max_length=20,null=True)
    rating=models.CharField(max_length=250,null=True)
    brand=models.CharField(max_length=250,null=True)
    asin=models.CharField(max_length=250,null=True)
    amazon_choice=models.CharField(max_length=250,null=True)
    product_url=models.CharField(max_length=700,null=True)
    task_id=models.UUIDField(null=False)
    account=models.ForeignKey(Account,on_delete=models.CASCADE,related_name='user_account_id',null=False)
    
    def __str__(self) -> str:
        return self.title or ""

    class Meta:
        ordering=['title', 'price']

amazon_crawler/views.py
import csv
import uuid
from django.db.models import Q
from django.contrib import auth
from django.contrib import messages
from django.shortcuts import render,redirect
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from amazon_crawler.models import EbayByProduct, AmazonByProduct
from accounts.task import scrape_ebay_by_products, scrape_amazon_products


def home(request):
    return render(request,'crawl.html')
            
@login_required
def ebay_by_products(request):
    current_user = auth.get_user(request)
    current_user_id=current_user.id
    current_site=get_current_site(request)
    
    if request.method=="POST":
        products_urls=request.POST.get('EBP')
        taskid=uuid.uuid4()
        if 'ebay' not in products_urls or "pgn=" in products_urls:
            messages.warning(request,f"""Please Paste valid URLS of ebey Products !"""    )
            return render(request,'ebay_by_products.html',{"UrlError":True})

        elif 'ebay' in products_urls:
            products_urls=products_urls.split()
            scrape_ebay_by_products.delay(products_urls,current_user_id,taskid,str(current_site))
            messages.success(request,f"""Your task : [{taskid}] has been added successfully, You will be notified as soon through email as job get finished !"""    )
            return render(request,'ebay_by_products.html',{"entities":"entities"})
    return render(request,'ebay_by_products.html')


@login_required
def amazon_by_pro(request):
    current_user = auth.get_user(request)
    current_user_id=current_user.id
    current_site=get_current_site(request)

    if request.method=="POST":
        products_urls=request.POST.get('ABP')
        taskid=uuid.uuid4()

        if 'amazon' not in products_urls:
            messages.warning(request,f"""Please Paste valid URLS of ebey Products !"""    )
            return render(request,'amazon_by_products.html',{"UrlError":True})

        if 'amazon' in products_urls:
            print("this is url",products_urls)
            products_urls=products_urls.split()
            messages.success(request,f"""Your task : [{taskid}] has been added successfully, You will be notified as soon through email as job get finished !"""    )
            scrape_amazon_products.delay(products_urls,current_user_id,taskid,str(current_site))
    return render(request,'amazon_by_products.html',{"UrlError":True})
 

@login_required
def download_data(request,task_id):
    if request.user.is_authenticated == True:
        current_user = auth.get_user(request)
        current_user=current_user.id
        response=HttpResponse(content_type='text/csv')
        writer=csv.writer(response)
        writer.writerow([
            "title","price",'rating',"shipping","condition",
            "brand","available_quantity","sold_quantity","img_url","product_url"])
        query_set=EbayByProduct.objects.filter(Q(account_id=int(current_user)) & Q(task_id=task_id)).values_list(
            "title","price",'rating',"condition","brand","available_quantity","sold_quantity","img_url","product_url",)

        for each in query_set:
            writer.writerow(each)
        response['Content-Disposition']='attachment; filename="Ebay-scraped.csv"'
        return response
    else:
        redirect ('login')

@login_required
def download_amazon(request,task_id):
    if request.user.is_authenticated ==True:
        current_user = auth.get_user(request)
        current_user=current_user.id

        response=HttpResponse(content_type='text/csv')
        writer=csv.writer(response)
        writer.writerow(["title","price","rating","brand","asin","amazon_choice","product_url"])
        query_set=AmazonByProduct.objects.filter(Q(account_id=int(current_user)) & Q(taskId=task_id)).values_list(
            "title","price","rating","brand","asin","amazon_choice","product_url")

        for each in query_set:
            writer.writerow(each)
        response['Content-Disposition']='attachment; filename="amazon-data-scraped.csv"'
        return response
    else:
        redirect ('login')

amazon_crawler/templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    
    <div id="message" class="container">
   `<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role='alert'> 
       <button type="button" class="close" data-dismiss="alert" > <span area-hidden="true">&times</span></button>
       

       {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
       {{message}}

    
    </div>
    </div>    
    {% endfor %}

{% endif %}

amazon_crawler/templates/includes/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2022 parsejet  </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">hussain@scrapysoft.com</span>
				<span  class="px-2">+92308-94-31-390</span>
				<span  class="px-2">developed by Shah Hussain</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


}

<script>
	
	$(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.mainImage img').attr('src', $(this).attr("href"));	
	}) })
	
	</script>

amazon_crawler/templates/includes/navbar.html
{% load static %}
<header class="section-header">
  <section class="header-main border-bottom bg-dark" style="height: 5rem;">
      <div class="container">


  <div class="row align-items-center" style="margin-top: -1mm;">
          <div class="category-wrap dropdown d-inline-block float-right">
              <button type="button" class="btn btn-primary dropdown-toggle bg-dark" data-toggle="dropdown"> 
                  <i class="fa fa-bars "></i> All Tools 
              </button>


              <button type="button" class="btn btn-primary bg-dark" > 
              <a href="{% url 'amazon_crawler:' %}" style="color:white;"> Home </a>
            
                </button>


              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'amazon_crawler:ABP' %}">Amazon Products </a>
                <a class="dropdown-item" href="{% url 'amazon_crawler:EBP' %}">Ebay products</a>
              
            </div>          </div>  
    
  <div></div>
  

      {% if user.is_authenticated  %}

      <div class="col-lg-10 col-sm-2 col-5 order-2 order-lg-1 text-light">
                  <div class="d-flex justify-content-end mb-3 mb-lg-0 ">
                      <div class="widget-header">
                          <div> 
                            
                            <div class="category-wrap dropdown d-inline-block float-right">
                              <button type="button" class="dropdown-toggle btn btn-outline-primary text-light" data-toggle="dropdown"> 
                                  {{ user.first_name }} 
                              </button>
                              <div class="dropdown-menu">
                                  <a class="dropdown-item" href="#">Edit Profile</a>
                                  <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                              </div>

                          </div>
                  </div>
              </div> <!-- col.// --> </div>

    
    {% else %}
    <div class="col-lg-10 col-sm-2 col-5 order-2 order-lg-1 text-light">
      <div class="d-flex justify-content-end mb-3 mb-lg-0 ">
          <div class="widget-header">
              <small class="title text-muted text-light">Welcome Guest !</small>
              <div> 
                  <a href="{% url 'accounts:login' %}" class="text-light">Sign in</a> <span class="dark-transp"> | </span>
                  <a href="{% url 'accounts:register' %}" class="text-light"> Register</a>
              </div>
      </div>
  </div> <!-- col.// --> </div>
  
    {% endif %}
          


  </div> <!-- row.// -->
      </div> <!-- container.// -->
  </section> <!-- header-main .// -->
  </header> <!-- section-header.// -->