accounts/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

import accounts
from . import views

app_name="accounts"

urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.view_login,name='login'),
    path('logout/',views.logouting,name='logout'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),
    path('forgotpassword',views.forgotPassword,name='forgotpassword'),
    path('resetpassword_validate/<uidb64>/<token>/',views.resetpassword_validate,name='resetpassword_validate'),
    path('resetpassword/',views.resetpassword,name='resetpassword')

]

amazon_crawler/urls.py
from django.urls import path
from . import views

app_name = "amazon_crawler"

# URLConf
urlpatterns = [
    path('', views.home, name=''),
    path('best-selling/', views.home, name='best-selling'),
    path('download/<task_id>/', views.download_data, name='download_data'),
    path('download_amazon/<task_id>/', views.download_amazon, name='download_amazon'),
    path("EBP/",views.ebay_by_products, name='EBP'),
    path("ABP/",views.amazon_by_pro, name='ABP')

            ]

crawler/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from amazon_crawler import views
from amazon_crawler import views
from django.conf.urls.static import static
from django.conf import settings

from crawler.settings import MEDIA_ROOT

admin.site.site_header = "ParseJet"

urlpatterns = [ path('admin/', admin.site.urls),
                #apps
                path('crawlers/', include('amazon_crawler.urls')),
                path('', views.home),
                path('accounts/',include('accounts.urls')),
                path('__debug__/', include(debug_toolbar.urls)),
                
                
                ] + static(settings.MEDIA_URL,document_root=MEDIA_ROOT)
                

                

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


# Create your models here.
class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("User must have an email address")

        if not username:
            raise ValueError("User must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    # phone_number = models.CharField(max_length=50)

    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = MyAccountManager()

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __unicode__(self):
        return "self.email"

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

amazon_crawler/models.py
from django.db import models
from accounts.models import Account


class EbayByProduct(models.Model):
    title = models.CharField(max_length=300, null=True)
    price = models.CharField(max_length=20, null=True)
    rating = models.CharField(max_length=20, null=True)
    condition = models.CharField(max_length=250, null=True) 
    brand = models.CharField(max_length=250, null=True) 
    available_quantity = models.CharField(max_length=250, null=True)  
    sold_quantity = models.CharField(max_length=250, null=True) 
    img_url = models.CharField(max_length=250, null=True)
    product_url=models.CharField(max_length=250,null=True)  
    task_id = models.UUIDField(null=False)  
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE,
        related_name='user_account', null=False
    )  
    
    def __str__(self) -> str:
        return self.title or ""

    class Meta:
        ordering = ['title', 'price']



class AmazonByProduct(models.Model):
    title=models.CharField(max_length=300,null=True)
    price=models.CharField(max_length=20,null=True)
    rating=models.CharField(max_length=250,null=True)
    brand=models.CharField(max_length=250,null=True)
    asin=models.CharField(max_length=250,null=True)
    amazon_choice=models.CharField(max_length=250,null=True)
    product_url=models.CharField(max_length=700,null=True)
    task_id=models.UUIDField(null=False)
    account=models.ForeignKey(Account,on_delete=models.CASCADE,related_name='user_account_id',null=False)
    
    def __str__(self) -> str:
        return self.title or ""

    class Meta:
        ordering=['title', 'price']

accounts/forms.py
from django import forms
from django.forms.models import ModelForm
from .models import Account

class Registration(ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        'Placeholder':"Password"
    })) 

    Repeat_password=forms.CharField(widget=forms.PasswordInput(attrs={
        'Placeholder':"Enter Password again"
    }))


    class Meta:
        model=Account
        fields=['first_name','last_name','email','username','password','Repeat_password']

    def __init__(self,*args,**kwargs):
        super(Registration,self).__init__(*args,**kwargs)
        self.fields['first_name'].widget.attrs['placeholder']=' Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder']=' Enter Last Name'
        self.fields['email'].widget.attrs['placeholder']='Email'
        self.fields['username'].widget.attrs['placeholder']='username'
        self.fields['password'].widget.attrs['placeholder']='Password'
        

        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'


    def clean(self):
        cleaned_data=super(Registration,self).clean()
        password=cleaned_data.get('password')
        Repeat_password=cleaned_data.get("Repeat_password")

        if password != Repeat_password:
            raise forms.ValidationError(
                "password does not match!"
            )
    
class Profile_update(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False) 
    # email = forms.CharField(required=False) 
    about_you = forms.CharField(required=False) 
    address = forms.CharField(required=False)

    class Meta:
        model=Account
        fields=['first_name','last_name','about_you','address']

accounts/views.py
from django.shortcuts import redirect, render
from accounts.forms import Registration, Profile_update

# from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Account
from django.urls import reverse_lazy

# activation email
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .task import sending_activation_mail


# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy("Amazon_crawler:best-selling"))

    if request.method == "POST":
        form = Registration(request.POST)
        context = {"form": form}
        if form.is_valid():
            current_site = get_current_site(request)
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            word = form.cleaned_data["password"]
            Repeat_password = form.cleaned_data["Repeat_password"]
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=word.strip(),
            )
            user.save()
            user_id = user.id

            sending_activation_mail.delay(
                "account_verification_email",
                str(current_site),
                user_id,
                email,
                "ParseJet Account Verification !",
            )  # Celery Job

            return redirect("/accounts/login/?command=verification&email=" + email)
    else:
        form = Registration()
        context = {"form": form}
    return render(request, "accounts/register.html", context)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! You are ready to go!. ")
        return redirect("accounts:login")
    else:
        messages.error(request, "Inavalid Activation Link ")
        return redirect("register")


def view_login(request):
    if request.user.is_authenticated == True:
        return redirect(reverse_lazy("Amazon_crawler:best-selling"))

    elif request.method == "POST":
        mail = request.POST.get("email")
        word = request.POST.get("password")
        user = authenticate(request, email=mail, password=word)

        if user is not None:
            login(request, user)
            # messages.SUCCESS(request,"You are now Login.")
            return redirect(reverse_lazy("Amazon_crawler:best-selling"))
        else:
            messages.error(request, "Invalid Login details !")
            return redirect("accounts:login")

    return render(request, "accounts/login.html")


@login_required
def logouting(request):
    logout(request)
    messages.success(request, "You are logged out.")
    return redirect("accounts:login")


# Recovering password sending email
def forgotPassword(request):
    if request.method == "POST":
        email = request.POST["email"]
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email=email)
            # Reset password
            current_site = get_current_site(request)
            user_id = user.id
            mail_subject = "ParseJet Reset Your Password"

            sending_activation_mail.delay(
                "reset_pass_email", str(current_site), user_id, email, mail_subject
            )  # Celery Job

            messages.success(
                request, "password Reset email has been send to your email address !"
            )
            return redirect("accounts:login")
        else:
            messages.error(request, "Account does not exists with this email!")
    return render(request, "accounts/forgotpassword.html")


# Validate the ssession and user
def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please Reset your Password")
        return redirect("resetpassword")
    else:
        messages.error(request, "Inavalid Reset Link!")
        return redirect("register")


# Update the password
def resetpassword(request):
    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]

        if password == confirm_password:
            uid = request.session.get("uid")
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Password changed succesfully !")
            return redirect("login")

        else:
            messages.error(request, "The Password did not match !")
            return redirect("resetpassword")
    else:
        return render(request, "accounts/resetpassword.html")


def ok(request):
    return HttpResponse(request, "ok")

amazon_crawler/views.py
import csv
import uuid
from django.db.models import Q
from django.contrib import auth
from django.contrib import messages
from django.shortcuts import render,redirect
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from amazon_crawler.models import EbayByProduct, AmazonByProduct
from accounts.task import scrape_ebay_by_products, scrape_amazon_products


def home(request):
    return render(request,'crawl.html')
            
@login_required
def ebay_by_products(request):
    current_user = auth.get_user(request)
    current_user_id=current_user.id
    current_site=get_current_site(request)
    
    if request.method=="POST":
        products_urls=request.POST.get('EBP')
        taskid=uuid.uuid4()
        if 'ebay' not in products_urls or "pgn=" in products_urls:
            messages.warning(request,f"""Please Paste valid URLS of ebey Products !"""    )
            return render(request,'ebay_by_products.html',{"UrlError":True})

        elif 'ebay' in products_urls:
            products_urls=products_urls.split()
            scrape_ebay_by_products.delay(products_urls,current_user_id,taskid,str(current_site))
            messages.success(request,f"""Your task : [{taskid}] has been added successfully, You will be notified as soon through email as job get finished !"""    )
            return render(request,'ebay_by_products.html',{"entities":"entities"})
    return render(request,'ebay_by_products.html')


@login_required
def amazon_by_pro(request):
    current_user = auth.get_user(request)
    current_user_id=current_user.id
    current_site=get_current_site(request)

    if request.method=="POST":
        products_urls=request.POST.get('ABP')
        taskid=uuid.uuid4()

        if 'amazon' not in products_urls:
            messages.warning(request,f"""Please Paste valid URLS of ebey Products !"""    )
            return render(request,'amazon_by_products.html',{"UrlError":True})

        if 'amazon' in products_urls:
            print("this is url",products_urls)
            products_urls=products_urls.split()
            messages.success(request,f"""Your task : [{taskid}] has been added successfully, You will be notified as soon through email as job get finished !"""    )
            scrape_amazon_products.delay(products_urls,current_user_id,taskid,str(current_site))
    return render(request,'amazon_by_products.html',{"UrlError":True})
 

@login_required
def download_data(request,task_id):
    if request.user.is_authenticated == True:
        current_user = auth.get_user(request)
        current_user=current_user.id
        response=HttpResponse(content_type='text/csv')
        writer=csv.writer(response)
        writer.writerow([
            "title","price",'rating',"shipping","condition",
            "brand","available_quantity","sold_quantity","img_url","product_url"])
        query_set=EbayByProduct.objects.filter(Q(account_id=int(current_user)) & Q(task_id=task_id)).values_list(
            "title","price",'rating',"condition","brand","available_quantity","sold_quantity","img_url","product_url",)

        for each in query_set:
            writer.writerow(each)
        response['Content-Disposition']='attachment; filename="Ebay-scraped.csv"'
        return response
    else:
        redirect ('login')

@login_required
def download_amazon(request,task_id):
    if request.user.is_authenticated ==True:
        current_user = auth.get_user(request)
        current_user=current_user.id

        response=HttpResponse(content_type='text/csv')
        writer=csv.writer(response)
        writer.writerow(["title","price","rating","brand","asin","amazon_choice","product_url"])
        query_set=AmazonByProduct.objects.filter(Q(account_id=int(current_user)) & Q(taskId=task_id)).values_list(
            "title","price","rating","brand","asin","amazon_choice","product_url")

        for each in query_set:
            writer.writerow(each)
        response['Content-Disposition']='attachment; filename="amazon-data-scraped.csv"'
        return response
    else:
        redirect ('login')

amazon_crawler/templates/accounts/account_verification_email.html
{% autoescape off %}

<html>
<hea>


</hea>
<body>

    <table
        style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;width:100%;background-color:#f6f6f6;margin:0"
        bgcolor="#f6f6f6">
        <tbody>
            <tr
                style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                <td style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;vertical-align:top;margin:0"
                    valign="top"></td>
                <td width="600"
                    style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;display:block!important;max-width:600px!important;clear:both!important;margin:0 auto"
                    valign="top">
                    <div
                        style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;max-width:600px;display:block;margin:0 auto;padding:20px">
                        <table width="100%" cellpadding="0" cellspacing="0"
                            style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;border-radius:3px;margin:0;border:none">
                            <tbody>
                                <tr
                                    style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                                    <td style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;vertical-align:top;margin:0;padding:30px;border:3px solid #67a8e4;border-radius:7px;background-color:#fff"
                                        valign="top">

                                        <table width="100%" cellpadding="0" cellspacing="0"
                                            style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                                            <tbody>
                                                <tr
                                                    style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                                                    <td style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;vertical-align:top;margin:0;padding:0 0 20px"
                                                        valign="top">
                                                        Hi {{user.first_name}}<br>
                                                        Thank you for registering with us. You are now part of a great
                                                        community
                                                    </td>
                                                </tr>

                                                <tr
                                                    style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                                                    <td style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;vertical-align:top;margin:0;padding:0 0 20px"
                                                        valign="top">
                                                        <a href="http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token  %}"
                                                            style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;color:#fff;text-decoration:none;line-height:2em;font-weight:bold;text-align:center;display:inline-block;border-radius:5px;text-transform:capitalize;background-color:#f06292;margin:0;border-color:#f06292;border-style:solid;border-width:8px 16px"
                                                            target="_blank">
                                                            Confirm account </a>
                                                    </td>
                                                </tr>



                                                <tr
                                                    style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                                                    <td style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;vertical-align:top;margin:0;padding:0 0 20px"
                                                        valign="top">
                                                        <b>ParseJet Team</b>
                                                        <p><small>"Believe in your dreams"</small></p>
                                                    </td>
                                                </tr>

                                                <tr
                                                    style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;margin:0">
                                                    <td style="text-align:center;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;vertical-align:top;margin:0;padding:0"
                                                        valign="top">
                                                        © 2022 ParseJet
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>




</body>

</html>

{% endautoescape %}

amazon_crawler/templates/accounts/forgotpassword.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
      <div class="card-body">
        
      <h4 class="card-title mb-4">Forgott Password</h4>
      {% include 'includes/alerts.html' %}
      
      <form action="{% url 'accounts:forgotpassword' %}" method="POST">
          {% csrf_token %}

          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name='email'>
          </div> <!-- form-group// -->
         
          
          <div class="form-group">
          	<a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Send  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>

<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}

amazon_crawler/templates/accounts/job_status.html
{% autoescape off %}

Hi {{user.first_name}},


    Your Job has been completed successfully !
    Job logs:

    scraped count:  {{count}} - type: {{type}}
    task_id      :  {{task_id}}
    download by  :  {{download_link}}
    

{% endautoescape %}

amazon_crawler/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

{% if request.GET.command == 'verification' %}
<div class="container mx-auto alert alert-info text-center" role="alert" style="max-width:1024px; margin-top:100px;">

  "Hey! we have send an activation link to your email [{{request.GET.email}}],click that to verify your account "
  <br><br>
  Already Verified? <a href="{% url 'accounts:login' %}">Login</a>

  </div>


{% else %}

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
        
      <h4 class="card-title mb-4">Sign in</h4>
      {% include 'includes/alerts.html' %}
      
      <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}

          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name='email'>
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name='password' >
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="{% url 'accounts:forgotpassword' %}" class="float-right">Forgot password?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>

<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endif %}

{% endblock %}

amazon_crawler/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
    <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
        <article class="card-body">

            {% include 'includes/alerts.html' %}
            <header class="mb-4">
                <h4 class="card-title">Sign up</h4>
            </header>

            <form action="{% url 'accounts:register' %}" method="POST">
                {% csrf_token %}

                <div class="form-row">
                    <div class="col form-group">
                        <label>First name</label>
                        {{form.first_name}}
                    </div> <!-- form-group end.// -->
                    <div class="col form-group">
                        <label>Last name</label>
                        {{form.last_name}}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row end.// -->

                <div class="form-row">
                    <div class="col form-group">
                        <label>Email</label>
                        {{form.email}}

                    </div> <!-- form-group end.// -->
                    <div class="col form-group">
                        <label>username</label>
                        {{form.username}}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row end.// -->

                <div class="form-row">
                    <div class="col form-group">
                        <label>Password</label>

                        {{form.password}}

                    </div> <!-- form-group end.// -->
                    <div class="col form-group">
                        <label>Confirm Password</label>
                        {{form.Repeat_password}}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row end.// -->


                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Register </button>
                </div> <!-- form-group// -->

                {{form.email.errors}}
                {{form.non_field_errors}}

            </form>
        </article><!-- card-body.// -->

    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
    <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}